<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PlatformSyncJobsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('platform_sync_jobs')->delete();
        
        \DB::table('platform_sync_jobs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'platform_id' => 1,
                'entity' => 'contest',
                'enabled' => 1,
                'priority' => 100,
                'interval_minutes' => 15,
                'last_started_at' => '2026-07-17 08:29:05',
                'last_finished_at' => '2026-07-17 08:29:07',
                'last_failed_at' => '2026-07-13 13:50:41',
                'last_success_at' => '2026-07-17 08:29:07',
                'last_error' => NULL,
                'metadata' => '{"exception":"TypeError","last_stats":{"checked":2130,"fetched":2130,"created":0,"updated":0,"failed":0,"skipped":2130,"metadata":{"platform":"codeforces","entity":"contest"}}}',
                'created_at' => '2026-07-11 17:44:29',
                'updated_at' => '2026-07-17 08:29:07',
            ),
            1 => 
            array (
                'id' => 2,
                'platform_id' => 1,
                'entity' => 'problem',
                'enabled' => 1,
                'priority' => 95,
                'interval_minutes' => 15,
                'last_started_at' => '2026-07-17 08:31:29',
                'last_finished_at' => '2026-07-17 08:32:13',
                'last_failed_at' => '2026-07-13 16:05:44',
                'last_success_at' => '2026-07-17 08:32:13',
                'last_error' => NULL,
                'metadata' => '{"exception":"TypeError","last_stats":{"checked":2130,"fetched":0,"created":0,"updated":0,"failed":24,"skipped":2106,"metadata":{"platform":"codeforces","entity":"problem"}}}',
                'created_at' => '2026-07-11 17:44:29',
                'updated_at' => '2026-07-17 08:32:13',
            ),
            2 => 
            array (
                'id' => 3,
                'platform_id' => 1,
                'entity' => 'user',
                'enabled' => 1,
                'priority' => 90,
                'interval_minutes' => 30,
                'last_started_at' => '2026-07-17 08:32:36',
                'last_finished_at' => '2026-07-17 08:32:36',
                'last_failed_at' => '2026-07-13 20:02:11',
                'last_success_at' => '2026-07-17 08:32:36',
                'last_error' => NULL,
                'metadata' => '{"exception":"TypeError","last_stats":{"checked":2,"fetched":0,"created":0,"updated":0,"failed":0,"skipped":2,"metadata":{"platform":"codeforces","entity":"user"}}}',
                'created_at' => '2026-07-11 17:44:29',
                'updated_at' => '2026-07-17 08:32:36',
            ),
            3 => 
            array (
                'id' => 4,
                'platform_id' => 1,
                'entity' => 'submission',
                'enabled' => 0,
                'priority' => 75,
                'interval_minutes' => 30,
                'last_started_at' => NULL,
                'last_finished_at' => NULL,
                'last_failed_at' => NULL,
                'last_success_at' => NULL,
                'last_error' => NULL,
                'metadata' => NULL,
                'created_at' => '2026-07-11 17:44:29',
                'updated_at' => '2026-07-11 17:44:29',
            ),
            4 => 
            array (
                'id' => 5,
                'platform_id' => 1,
                'entity' => 'standing',
                'enabled' => 0,
                'priority' => 80,
                'interval_minutes' => 30,
                'last_started_at' => NULL,
                'last_finished_at' => NULL,
                'last_failed_at' => NULL,
                'last_success_at' => NULL,
                'last_error' => NULL,
                'metadata' => NULL,
                'created_at' => '2026-07-11 17:44:29',
                'updated_at' => '2026-07-11 17:44:29',
            ),
            5 => 
            array (
                'id' => 6,
                'platform_id' => 1,
                'entity' => 'rating_change',
                'enabled' => 0,
                'priority' => 70,
                'interval_minutes' => 30,
                'last_started_at' => NULL,
                'last_finished_at' => NULL,
                'last_failed_at' => NULL,
                'last_success_at' => NULL,
                'last_error' => NULL,
                'metadata' => NULL,
                'created_at' => '2026-07-11 17:44:29',
                'updated_at' => '2026-07-11 17:44:29',
            ),
            6 => 
            array (
                'id' => 7,
                'platform_id' => 1,
                'entity' => 'user_rating_history',
                'enabled' => 1,
                'priority' => 85,
                'interval_minutes' => 30,
                'last_started_at' => '2026-07-17 08:32:36',
                'last_finished_at' => '2026-07-17 08:32:36',
                'last_failed_at' => NULL,
                'last_success_at' => '2026-07-17 08:32:36',
                'last_error' => NULL,
                'metadata' => '{"last_stats":{"checked":2,"fetched":0,"created":0,"updated":0,"failed":0,"skipped":2,"metadata":{"platform":"codeforces","entity":"user_rating_history"}}}',
                'created_at' => '2026-07-11 17:44:29',
                'updated_at' => '2026-07-17 08:32:36',
            ),
            7 => 
            array (
                'id' => 8,
                'platform_id' => 1,
                'entity' => 'user_submissions',
                'enabled' => 1,
                'priority' => 85,
                'interval_minutes' => 30,
                'last_started_at' => '2026-07-17 08:32:36',
                'last_finished_at' => '2026-07-17 08:32:37',
                'last_failed_at' => '2026-07-16 17:02:46',
                'last_success_at' => '2026-07-17 08:32:37',
                'last_error' => NULL,
                'metadata' => '{"exception":"Error","last_stats":{"checked":2,"fetched":0,"created":0,"updated":0,"failed":0,"skipped":2,"metadata":{"platform":"codeforces","entity":"user_submission"}}}',
                'created_at' => '2026-07-11 17:44:29',
                'updated_at' => '2026-07-17 08:32:37',
            ),
            8 => 
            array (
                'id' => 9,
                'platform_id' => 2,
                'entity' => 'contest',
                'enabled' => 1,
                'priority' => 100,
                'interval_minutes' => 15,
                'last_started_at' => '2026-07-17 08:29:07',
                'last_finished_at' => '2026-07-17 08:31:29',
                'last_failed_at' => '2026-07-14 08:17:08',
                'last_success_at' => '2026-07-17 08:31:29',
                'last_error' => NULL,
                'metadata' => '{"exception":"Illuminate\\\\Http\\\\Client\\\\ConnectionException","last_stats":{"checked":6205,"fetched":6205,"created":2,"updated":0,"failed":0,"skipped":6203,"metadata":{"platform":"atcoder","entity":"contest"}}}',
                'created_at' => '2026-07-11 17:44:29',
                'updated_at' => '2026-07-17 08:31:29',
            ),
            9 => 
            array (
                'id' => 10,
                'platform_id' => 2,
                'entity' => 'problem',
                'enabled' => 1,
                'priority' => 95,
                'interval_minutes' => 15,
                'last_started_at' => '2026-07-17 08:32:13',
                'last_finished_at' => '2026-07-17 08:32:36',
                'last_failed_at' => '2026-07-13 20:02:07',
                'last_success_at' => '2026-07-17 08:32:36',
                'last_error' => NULL,
                'metadata' => '{"exception":"TypeError","last_stats":{"checked":6204,"fetched":14,"created":0,"updated":14,"failed":11,"skipped":6191,"metadata":{"platform":"atcoder","entity":"problem"}}}',
                'created_at' => '2026-07-11 17:44:29',
                'updated_at' => '2026-07-17 08:32:36',
            ),
            10 => 
            array (
                'id' => 11,
                'platform_id' => 2,
                'entity' => 'user',
                'enabled' => 1,
                'priority' => 90,
                'interval_minutes' => 30,
                'last_started_at' => '2026-07-17 08:32:36',
                'last_finished_at' => '2026-07-17 08:32:36',
                'last_failed_at' => '2026-07-13 20:02:13',
                'last_success_at' => '2026-07-17 08:32:36',
                'last_error' => NULL,
                'metadata' => '{"exception":"TypeError","last_stats":{"checked":2,"fetched":0,"created":0,"updated":0,"failed":0,"skipped":2,"metadata":{"platform":"atcoder","entity":"user"}}}',
                'created_at' => '2026-07-11 17:44:29',
                'updated_at' => '2026-07-17 08:32:36',
            ),
            11 => 
            array (
                'id' => 12,
                'platform_id' => 2,
                'entity' => 'submission',
                'enabled' => 0,
                'priority' => 75,
                'interval_minutes' => 30,
                'last_started_at' => NULL,
                'last_finished_at' => NULL,
                'last_failed_at' => NULL,
                'last_success_at' => NULL,
                'last_error' => NULL,
                'metadata' => NULL,
                'created_at' => '2026-07-11 17:44:29',
                'updated_at' => '2026-07-11 17:44:29',
            ),
            12 => 
            array (
                'id' => 13,
                'platform_id' => 2,
                'entity' => 'standing',
                'enabled' => 0,
                'priority' => 80,
                'interval_minutes' => 30,
                'last_started_at' => NULL,
                'last_finished_at' => NULL,
                'last_failed_at' => NULL,
                'last_success_at' => NULL,
                'last_error' => NULL,
                'metadata' => NULL,
                'created_at' => '2026-07-11 17:44:29',
                'updated_at' => '2026-07-11 17:44:29',
            ),
            13 => 
            array (
                'id' => 14,
                'platform_id' => 2,
                'entity' => 'rating_change',
                'enabled' => 0,
                'priority' => 70,
                'interval_minutes' => 30,
                'last_started_at' => NULL,
                'last_finished_at' => NULL,
                'last_failed_at' => NULL,
                'last_success_at' => NULL,
                'last_error' => NULL,
                'metadata' => NULL,
                'created_at' => '2026-07-11 17:44:29',
                'updated_at' => '2026-07-11 17:44:29',
            ),
            14 => 
            array (
                'id' => 15,
                'platform_id' => 2,
                'entity' => 'user_rating_history',
                'enabled' => 1,
                'priority' => 85,
                'interval_minutes' => 30,
                'last_started_at' => '2026-07-17 08:32:37',
                'last_finished_at' => '2026-07-17 08:32:37',
                'last_failed_at' => NULL,
                'last_success_at' => '2026-07-17 08:32:37',
                'last_error' => NULL,
                'metadata' => '{"last_stats":{"checked":2,"fetched":0,"created":0,"updated":0,"failed":0,"skipped":2,"metadata":{"platform":"atcoder","entity":"user_rating_history"}}}',
                'created_at' => '2026-07-11 17:44:29',
                'updated_at' => '2026-07-17 08:32:37',
            ),
            15 => 
            array (
                'id' => 16,
                'platform_id' => 2,
                'entity' => 'user_submissions',
                'enabled' => 1,
                'priority' => 85,
                'interval_minutes' => 30,
                'last_started_at' => '2026-07-17 08:32:37',
                'last_finished_at' => '2026-07-17 08:32:58',
                'last_failed_at' => '2026-07-16 17:02:46',
                'last_success_at' => '2026-07-17 08:32:58',
                'last_error' => NULL,
                'metadata' => '{"exception":"Error","last_stats":{"checked":2,"fetched":0,"created":0,"updated":0,"failed":0,"skipped":12404,"metadata":{"platform":"atcoder","entity":"user_submission"}}}',
                'created_at' => '2026-07-11 17:44:29',
                'updated_at' => '2026-07-17 08:32:58',
            ),
        ));
        
        
    }
}