<?php

namespace App\Platforms\AtCoder\Services;

use Illuminate\Support\Facades\Http;

class AtCoderTitleTranslatorService
{
    private const DICTIONARY = [
        'World Artificial Intelligence Programming Contest日本国内最終予選' => ' World Artificial Intelligence Programming Contest Japan Final Qualifier ',
        'ZONeエナジー プログラミングコンテスト' => ' ZONe Energy Programming Contest ',
        '三井住友信託銀行プログラミングコンテスト' => ' Sumitomo Mitsui Trust Bank Programming Contest ',
        '技術室奥プログラミングコンテスト' => ' Technical Room Programming Contest ',
        '全国統一プログラミング王決定戦' => ' Japan Unified Programming King Contest ',
        '天下一プログラマーコンテスト' => ' Tenkaichi Programmer Contest ',
        '新ジャッジテストコンテスト' => ' New Judge Test Contest ',
        'すぬけのお誕生日コンテスト' => ' Snuke Birthday Contest ',
        'おいしいたこ焼きの作り方' => ' How to Make Delicious Takoyaki ',
        'おいしいたこ焼きの食べ方' => ' How to Eat Delicious Takoyaki ',
        'おいしいたこ焼きの売り方' => ' How to Sell Delicious Takoyaki ',
        'おいしいたこ焼きの焼き方' => ' How to Cook Delicious Takoyaki ',
        'ディスカバリーチャンネル' => ' Discovery Channel ',
        'プログラミングコンテスト' => ' Programming Contest ',
        'デジタルの日特別イベント' => ' Digital Day Special Event ',
        '新概念コンピューティング' => ' New Concept Computing ',
        'パ研合宿コンペティション' => ' Paken Camp Competition ',
        'スフィンクスのなぞなぞ' => ' Sphinx\'s Riddle ',
        'プログラミング王決定戦' => ' Programming King Contest ',
        'セミファイナルステージ' => ' Semi-Final Stage ',
        'ウクーニャたんお誕生日' => ' Ukunya Birthday ',
        'アルゴリズム実技検定' => ' Practical Algorithm Skill Test ',
        'ドワンゴからの挑戦状' => ' Dwango Challenge ',
        '日本情報オリンピック' => ' Japanese Olympiad in Informatics ',
        '灘校文化祭コンテスト' => ' Nada High School Festival Contest ',
        'オンサイトコンテスト' => ' Onsite Contest ',
        'トランプ挿入ソート' => ' Trump Insertion Sort ',
        '天下一プログラマー' => ' Tenkaichi Programmer ',
        'プロコンチャレンジ' => ' Procon Challenge ',
        '社会システム事業部' => ' Social System Division ',
        'アルゴリズムと数学' => ' Algorithms and Math ',
        'オンラインジャッジ' => ' Online Judge ',
        '日本代表選手選考会' => ' Japan Representative Selection ',
        'ファイナルステージ' => ' Final Stage ',
        'オープンコンテスト' => ' Open Contest ',
        'チップ・ストーリー' => ' Chip Story ',
        'トリボナッチ数列' => ' Tribonacci Sequence ',
        '三井住友信託銀行' => ' Sumitomo Mitsui Trust Bank ',
        'コードコンテスト' => ' Code Contest ',
        'プロコンオープン' => ' Procon Open ',
        'エクサウィザーズ' => ' ExaWizards ',
        'ユニークビジョン' => ' Unique Vision ',
        'みんなのプロコン' => ' Everyone\'s Procon ',
        'コンペティション' => ' Competition ',
        '日本国内最終予選' => ' Japan National Final Qualifier ',
        '新エディタテスト' => ' New Editor Test ',
        'ソーシャルゲーム' => ' Social Game ',
        'シミュレーション' => ' Simulation ',
        '感雨時刻の整理' => ' Rainfall Time Organization ',
        '禁止された数字' => ' Forbidden Numbers ',
        '幾何コンテスト' => ' Geometry Contest ',
        'あーだこーだー' => ' Ada Koda ',
        'DNA配列解析' => ' DNA Sequence Analysis ',
        'プログラミング' => ' Programming ',
        'ハーフマラソン' => ' Half Marathon ',
        'チャレンジャー' => ' Challenger ',
        'ディスカバリー' => ' Discovery ',
        '季トレーニング' => ' Season Training ',
        'エキシビション' => ' Exhibition ',
        'エキシビジョン' => ' Exhibition ',
        'ある勇者の物語' => ' A Hero\'s Tale ',
        'トリッキー問題' => ' Tricky Problems ',
        '伝説の団子職人' => ' Legendary Dango Craftsman ',
        'ビジュアライザ' => ' Visualizer ',
        'スタンプラリー' => ' Stamp Rally ',
        '高橋君と青木君' => ' Takahashi and Aoki ',
        '深さ優先探索' => ' Depth First Search ',
        'デジタルの日' => ' Digital Day ',
        '特別イベント' => ' Special Event ',
        '高レート人材' => ' High Rate Talent ',
        'アルゴリズム' => ' Algorithms ',
        'プログラマー' => ' Programmer ',
        'パナソニック' => ' Panasonic ',
        'トヨタ自動車' => ' Toyota Motor ',
        '東京海上日動' => ' Tokio Marine & Nichido ',
        'いろはちゃん' => ' Iroha-chan ',
        '国内最終予選' => ' National Final Qualifier ',
        'トレーニング' => ' Training ',
        '装置実装部門' => ' Device Implementation Division ',
        '早解きリレー' => ' Speed Relay ',
        '負荷チェック' => ' Load Check ',
        '東京工業大学' => ' Tokyo Institute of Technology ',
        '慶應義塾大学' => ' Keio University ',
        '電気通信大学' => ' University of Electro-Communications ',
        'すぬけそだて' => ' Raising Snuke ',
        'ボードゲーム' => ' Board Game ',
        'カードゲーム' => ' Card Game ',
        'しゃくとり法' => ' Two Pointers ',
        '石取りゲーム' => ' Nim Game ',
        '実行時間制限' => ' Time Limit ',
        '視程の通報' => ' Visibility Report ',
        '辞書式順序' => ' Lexicographical Order ',
        '幅優先探索' => ' Breadth First Search ',
        '新ジャッジ' => ' New Judge ',
        '灘校文化祭' => ' Nada High School Festival ',
        'コンテスト' => ' Contest ',
        'チャレンジ' => ' Challenge ',
        'キーエンス' => ' Keyence ',
        'ヤマト運輸' => ' Yamato Transport ',
        'エイシング' => ' Aising ',
        '日立製作所' => ' Hitachi ',
        '日立新概念' => ' Hitachi New Concept ',
        '高校生大会' => ' High School Championship ',
        '演習問題集' => ' Practice Problems ',
        '競プロ典型' => ' Competitive Programming Typical ',
        'チーム対抗' => ' Team Competition ',
        '模擬練習会' => ' Practice Session ',
        'マスターズ' => ' Masters ',
        'トリッキー' => ' Tricky ',
        'オンサイト' => ' Onsite ',
        '早稲田大学' => ' Waseda University ',
        '北海道大学' => ' Hokkaido University ',
        '名古屋大学' => ' Nagoya University ',
        '最悪の記者' => ' Worst Journalist ',
        '半導体工場' => ' Semiconductor Factory ',
        '勇者ビ太郎' => ' Hero BiTaro ',
        'ビ太郎の旅' => ' BiTaro\'s Journey ',
        'テレビ放送' => ' TV Broadcast ',
        '章について' => ' About Section ',
        'シムロード' => ' SimRoad ',
        'ピラミッド' => ' Pyramid ',
        'りんごさん' => ' Ringo ',
        '二部グラフ' => ' Bipartite Graph ',
        '最大公約数' => ' Greatest Common Divisor ',
        '最小公倍数' => ' Least Common Multiple ',
        '動的計画法' => ' Dynamic Programming ',
        '組み合わせ' => ' Combination ',
        '塗りつぶし' => ' Fill ',
        'メモリ制限' => ' Memory Limit ',
        '積雪深差' => ' Snow Depth Difference ',
        '風力観測' => ' Wind Observation ',
        '入れ替え' => ' Swap ',
        'マーブル' => ' Marble ',
        'アルバム' => ' Album ',
        '技術室奥' => ' Technical Room ',
        'ゲノコン' => ' GenoCon ',
        'プロコン' => ' Procon ',
        'マラソン' => ' Marathon ',
        'ドワンゴ' => ' Dwango ',
        'みんなの' => ' Everyone\'s ',
        'えびまの' => ' Ebima\'s ',
        'すぬけの' => ' Snuke\'s ',
        'パ研合宿' => ' Paken Camp ',
        '追いコン' => ' Farewell Party ',
        '全国統一' => ' Japan Unified ',
        '王決定戦' => ' Championship ',
        '国内最終' => ' National Final ',
        '実技検定' => ' Practical Skill Test ',
        '代替措置' => ' Alternative Measure ',
        '装置実装' => ' Device Implementation ',
        'オープン' => ' Open ',
        '特別配信' => ' Special Stream ',
        '企業対抗' => ' Corporate Competition ',
        'あさぷろ' => ' Morning Procon ',
        '深夜の部' => ' Midnight Session ',
        'お誕生日' => ' Birthday ',
        '周年記念' => ' Anniversary ',
        '東京大学' => ' University of Tokyo ',
        '東北大学' => ' Tohoku University ',
        '京都大学' => ' Kyoto University ',
        '大阪大学' => ' Osaka University ',
        '筑波大学' => ' University of Tsukuba ',
        '神戸大学' => ' Kobe University ',
        '九州大学' => ' Kyushu University ',
        '広島大学' => ' Hiroshima University ',
        '日本最強' => ' Japan Strongest ',
        '慶應義塾' => ' Keio ',
        '曲芸飛行' => ' Aerobatics ',
        '鉄道旅行' => ' Train Travel ',
        'チーム戦' => ' Team Battle ',
        'の飛行場' => ' Airfield ',
        'すごろく' => ' Sugoroku ',
        'ロボット' => ' Robot ',
        'ポスター' => ' Poster ',
        'ペースト' => ' Paste ',
        '高橋君と' => ' Takahashi and ',
        '青木君と' => ' Aoki and ',
        'すぬけ君' => ' Snuke ',
        '二分探索' => ' Binary Search ',
        'グリッド' => ' Grid ',
        '根付き木' => ' Rooted Tree ',
        '最短経路' => ' Shortest Path ',
        '部分集合' => ' Subset ',
        '並べ替え' => ' Sort ',
        'スワップ' => ' Swap ',
        'サイコロ' => ' Dice ',
        'スイッチ' => ' Switches ',
        '市松模様' => ' Checkerboard Pattern ',
        '塗り分け' => ' Coloring ',
        'チェック' => ' Check ',
        '数え上げ' => ' Counting ',
        '植木算' => ' Planting Trees Arithmetic ',
        '正直者' => ' Honest Person ',
        '天下一' => ' Tenkaichi ',
        '復習用' => ' For Practice ',
        'パ研杯' => ' Paken Cup ',
        '大手前' => ' Otemae ',
        'セット' => ' Set ',
        '実課題' => ' Real World Tasks ',
        'の鉄則' => ' Fundamentals ',
        '増刊号' => ' Extra Edition ',
        'リレー' => ' Relay ',
        '夜の部' => ' Night Session ',
        '昼の部' => ' Day Session ',
        'テスト' => ' Test ',
        '過去問' => ' Past Problems ',
        '問題集' => ' Problem Set ',
        '謎解き' => ' Riddle Solving ',
        'バトル' => ' Battle ',
        'まとめ' => ' Summary ',
        '挑戦状' => ' Challenge ',
        'さんの' => ' \'s ',
        '論応援' => ' Thesis Support ',
        'ふか杯' => ' Fuka Cup ',
        '日本橋' => ' Nihonbashi ',
        '早稲田' => ' Waseda ',
        '第一回' => ' 1st Round ',
        '第二回' => ' 2nd Round ',
        '第三回' => ' 3rd Round ',
        '第四回' => ' 4th Round ',
        '第五回' => ' 5th Round ',
        '第六回' => ' 6th Round ',
        '第七回' => ' 7th Round ',
        '第八回' => ' 8th Round ',
        '第九回' => ' 9th Round ',
        '第十回' => ' 10th Round ',
        '第1日' => ' Day 1 ',
        '第2日' => ' Day 2 ',
        '第3日' => ' Day 3 ',
        '第4日' => ' Day 4 ',
        '1日目' => ' Day 1 ',
        '2日目' => ' Day 2 ',
        '3日目' => ' Day 3 ',
        '4日目' => ' Day 4 ',
        '選手権' => ' Championship ',
        'リーグ' => ' League ',
        '長方形' => ' Rectangle ',
        '足し算' => ' Addition ',
        '引き算' => ' Subtraction ',
        '掛け算' => ' Multiplication ',
        '割り算' => ' Division ',
        'コピー' => ' Copy ',
        '高橋君' => ' Takahashi ',
        '青木君' => ' Aoki ',
        'すぬけ' => ' Snuke ',
        'りんご' => ' Ringo ',
        'うさぎ' => ' Rabbit ',
        'アリス' => ' Alice ',
        '貪欲法' => ' Greedy Algorithm ',
        '全探索' => ' Exhaustive Search ',
        '文字列' => ' String ',
        '自然数' => ' Natural Number ',
        'グラフ' => ' Graph ',
        '最大値' => ' Maximum Value ',
        '最小値' => ' Minimum Value ',
        '最大化' => ' Maximize ',
        '最小化' => ' Minimize ',
        '中央値' => ' Median ',
        '期待値' => ' Expected Value ',
        '公約数' => ' Common Divisor ',
        '公倍数' => ' Common Multiple ',
        'あまり' => ' Remainder ',
        '正の数' => ' Positive Number ',
        '負の数' => ' Negative Number ',
        '絶対値' => ' Absolute Value ',
        '平方根' => ' Square Root ',
        '平方数' => ' Square Number ',
        '立方数' => ' Cube Number ',
        'ソート' => ' Sort ',
        'コイン' => ' Coins ',
        'ボール' => ' Balls ',
        'ボタン' => ' Buttons ',
        'ライト' => ' Lights ',
        'カード' => ' Cards ',
        'ゲーム' => ' Game ',
        'パズル' => ' Puzzle ',
        'クイズ' => ' Quiz ',
        'ビ太郎' => ' BiTaro ',
        '部分点' => ' Partial Points ',
        '難易度' => ' Difficulty ',
        'ちゃん' => ' ',
        '直訴' => ' Direct Appeal ',
        '派閥' => ' Faction ',
        '流行' => ' Fashion ',
        '日立' => ' Hitachi ',
        'パ研' => ' Paken ',
        '鉄則' => ' Fundamentals ',
        'なう' => ' Now ',
        '部門' => ' Division ',
        '予選' => ' Qualifier ',
        '本戦' => ' Main Round ',
        '本選' => ' Main Round ',
        '決勝' => ' Finals ',
        '日程' => ' Schedule ',
        '競技' => ' Competitive ',
        '創立' => ' Anniversary ',
        '周年' => ' Anniversary ',
        '記念' => ' Anniversary ',
        '問題' => ' Problems ',
        '合宿' => ' Camp ',
        '新刊' => ' New Publication ',
        '集結' => ' Gathering ',
        '幾何' => ' Geometry ',
        '数学' => ' Math ',
        '北大' => ' Hokkaido University ',
        '大学' => ' University ',
        '日本' => ' Japan ',
        '東京' => ' Tokyo ',
        '東北' => ' Tohoku ',
        '上海' => ' Shanghai ',
        '一次' => ' Primary ',
        '二次' => ' Secondary ',
        '日目' => '  Day  ',
        '学生' => ' Student ',
        '入門' => ' Introduction ',
        '題' => ' Problems ',
        '問' => ' Problems ',
        '挑' => ' Challenge ',
        '夏' => ' Summer ',
        '秋' => ' Autumn ',
        '冬' => ' Winter ',
        '春' => ' Spring ',
        '第' => ' Round  ',
        '回' => '   ',
        '年' => '   ',
        '一' => ' 1 ',
        '二' => ' 2 ',
        '三' => ' 3 ',
        '四' => ' 4 ',
        '五' => ' 5 ',
        '六' => ' 6 ',
        '七' => ' 7 ',
        '八' => ' 8 ',
        '九' => ' 9 ',
        '十' => ' 10 ',
        '戦' => ' Match ',
    ];

    /**
     * Translate Japanese text/title into English using Dictionary + Google Translate API.
     */
    public function translate(string $text): string
    {
        if (trim($text) === '') {
            return $text;
        }

        $translated = strtr($text, self::DICTIONARY);

        if (preg_match('/[\x{4E00}-\x{9FBF}\x{3040}-\x{309F}\x{30A0}-\x{30FF}]/u', $translated)) {
            try {
                $url = 'https://translate.googleapis.com/translate_a/single?client=gtx&sl=ja&tl=en&dt=t&q=' . urlencode($translated);
                $response = Http::timeout(5)
                    ->withHeaders([
                        'User-Agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36',
                    ])
                    ->get($url);

                if ($response->successful()) {
                    $json = $response->json();
                    if (isset($json[0][0][0])) {
                        $translated = (string) $json[0][0][0];
                    }
                }
            } catch (\Throwable $e) {
                // Fallback to dictionary translation
            }
        }

        $clean = preg_replace('/[\x{4E00}-\x{9FBF}\x{3040}-\x{309F}\x{30A0}-\x{30FF}]/u', '', $translated);
        $clean = trim((string) preg_replace('/\s+/', ' ', $clean));

        return $clean !== '' ? $clean : $text;
    }

    /**
     * Format English title for AtCoder contests (supporting parentheses extraction, ABC/ARC/AGC/AHC indexing).
     */
    public function formatContestTitle(string $contestId, string $rawTitle): string
    {
        if (preg_match('/[（\(]\s*([A-Za-z0-9\s\-_\.\#]+)[）\)]/u', $rawTitle, $m)) {
            $parenthesesTitle = trim($m[1]);
            if (strlen($parenthesesTitle) > 3) {
                return $parenthesesTitle;
            }
        }

        $lowerId = strtolower($contestId);

        if (preg_match('/^abc(\d+)/', $lowerId, $m)) {
            return 'AtCoder Beginner Contest ' . (int) $m[1];
        }
        if (preg_match('/^arc(\d+)/', $lowerId, $m)) {
            return 'AtCoder Regular Contest ' . (int) $m[1];
        }
        if (preg_match('/^agc(\d+)/', $lowerId, $m)) {
            return 'AtCoder Grand Contest ' . (int) $m[1];
        }
        if (preg_match('/^ahc(\d+)/', $lowerId, $m)) {
            return 'AtCoder Heuristic Contest ' . (int) $m[1];
        }

        return $this->translate($rawTitle);
    }
}
